import type { DramaEpisode } from './types'

export const fixedDramas: DramaEpisode[] = [
  {
    id: 1,
    title: 'The Fake Heiress',
    hook: 'She stole her identity for 3 years, now the real daughter is back',
    genre: 'identity_swap',
    coverImage: '/images/drama-1.jpg',
    messages: [
      {
        id: 'msg-1-1',
        sender: 'Xiaoya',
        text: "You don't *deserve* to be here! You're just a poor nobody!",
        vocabs: [{ word: 'deserve', type: 'highlight' }],
        isImage: false,
      },
      {
        id: 'msg-1-2',
        sender: 'Lin Wei',
        text: 'Is that so?',
        vocabs: [],
        isImage: false,
      },
      {
        id: 'msg-1-3',
        sender: 'Xiaoya',
        text: "Everyone knows I'm the real daughter of the Lin family. You're nothing!",
        vocabs: [],
        isImage: false,
      },
      {
        id: 'msg-1-4',
        sender: 'Lin Wei',
        text: 'I have the DNA test results right here. Want to see them?',
        vocabs: [],
        isImage: false,
      },
      {
        id: 'msg-1-5',
        sender: 'Xiaoya',
        text: "What? No, that's impossible!",
        vocabs: [],
        isImage: false,
      },
      {
        id: 'msg-1-6',
        sender: 'Lin Wei',
        text: "I'm very *confident* the police will be interested in your fraud case.",
        vocabs: [{ word: 'confident', type: 'highlight' }],
        isImage: false,
      },
      {
        id: 'msg-1-7',
        sender: 'Xiaoya',
        text: "Please! I'll give everything back! I'll leave the city!",
        vocabs: [],
        isImage: false,
      },
      {
        id: 'msg-1-8',
        sender: 'Lin Wei',
        text: 'You should *apologize* to my parents first. You lied to them for three years.',
        vocabs: [{ word: 'apologize', type: 'highlight' }],
        isImage: false,
      },
      {
        id: 'msg-1-9',
        sender: 'Xiaoya',
        text: 'I'm sorry! I was wrong about everything!',
        vocabs: [],
        isImage: false,
      },
      {
        id: 'msg-1-10',
        sender: 'Lin Wei',
        text: 'Too late. The police are already waiting outside.',
        vocabs: [],
        isImage: false,
      },
    ],
  },
  {
    id: 2,
    title: "The CEO's Ex-Wife",
    hook: "He divorced her for being useless, now she's his boss",
    genre: 'revenge',
    coverImage: '/images/drama-2.jpg',
    messages: [
      {
        id: 'msg-2-1',
        sender: 'Zhang Wei',
        text: "Sign these papers! You're *useless* to me!",
        vocabs: [{ word: 'useless', type: 'highlight' }],
        isImage: false,
      },
      {
        id: 'msg-2-2',
        sender: 'Lili',
        text: "Fine. I'll sign.",
        vocabs: [],
        isImage: false,
      },
      {
        id: 'msg-2-3',
        sender: 'Zhang Wei',
        text: 'Good. Now get out of my house.',
        vocabs: [],
        isImage: false,
      },
      {
        id: 'msg-2-4',
        sender: 'Lili',
        text: 'Actually, this is my house. I bought it last year.',
        vocabs: [],
        isImage: false,
      },
      {
        id: 'msg-2-5',
        sender: 'Zhang Wei',
        text: 'What? How did you get so much money?',
        vocabs: [],
        isImage: false,
      },
      {
        id: 'msg-2-6',
        sender: 'Lili',
        text: "I'm the CEO of Chen Corporation. Your company's biggest client.",
        vocabs: [],
        isImage: false,
      },
      {
        id: 'msg-2-7',
        sender: 'Zhang Wei',
        text: 'Lili, I was wrong! Can we talk?',
        vocabs: [],
        isImage: false,
      },
      {
        id: 'msg-2-8',
        sender: 'Lili',
        text: "I'm very *successful* now. I don't have time for failures.",
        vocabs: [{ word: 'successful', type: 'highlight' }],
        isImage: false,
      },
      {
        id: 'msg-2-9',
        sender: 'Zhang Wei',
        text: 'I *regret* everything! Please give me another chance!',
        vocabs: [{ word: 'regret', type: 'highlight' }],
        isImage: false,
      },
    ],
  },
  {
    id: 3,
    title: 'The Janitor Billionaire',
    hook: 'She threw money at the janitor, not knowing he owns the building',
    genre: 'hidden_identity',
    coverImage: '/images/drama-3.jpg',
    messages: [
      {
        id: 'msg-3-1',
        sender: 'Mrs. Chen',
        text: "Take this money and leave! You're just a *poor* janitor!",
        vocabs: [{ word: 'poor', type: 'highlight' }],
        isImage: false,
      },
      {
        id: 'msg-3-2',
        sender: 'Xiaoming',
        text: "I don't need your money.",
        vocabs: [],
        isImage: false,
      },
      {
        id: 'msg-3-3',
        sender: 'Mrs. Chen',
        text: 'How dare you refuse me? Do you know who I am?',
        vocabs: [],
        isImage: false,
      },
      {
        id: 'msg-3-4',
        sender: 'Xiaoming',
        text: "I'm the owner of this building. You have 24 hours to move out.",
        vocabs: [],
        isImage: false,
      },
      {
        id: 'msg-3-5',
        sender: 'Mrs. Chen',
        text: "What? That's impossible!",
        vocabs: [],
        isImage: false,
      },
      {
        id: 'msg-3-6',
        sender: 'Xiaoming',
        text: "I'm actually very *wealthy*. Check the property records.",
        vocabs: [{ word: 'wealthy', type: 'highlight' }],
        isImage: false,
      },
      {
        id: 'msg-3-7',
        sender: 'Mrs. Chen',
        text: 'Please! I was wrong! Give me another chance!',
        vocabs: [],
        isImage: false,
      },
      {
        id: 'msg-3-8',
        sender: 'Xiaoming',
        text: 'You should learn to *respect* everyone, not just rich people.',
        vocabs: [{ word: 'respect', type: 'highlight' }],
        isImage: false,
      },
    ],
  },
  {
    id: 4,
    title: "The Mother-in-Law's Shock",
    hook: 'She bullied her daughter-in-law for years, until she found out the truth',
    genre: 'family_drama',
    coverImage: '/images/drama-4.jpg',
    messages: [
      {
        id: 'msg-4-1',
        sender: 'Mrs. Wang',
        text: "You're too *weak*! My son deserves better!",
        vocabs: [{ word: 'weak', type: 'highlight' }],
        isImage: false,
      },
      {
        id: 'msg-4-2',
        sender: 'Meimei',
        text: 'Is that what you think?',
        vocabs: [],
        isImage: false,
      },
      {
        id: 'msg-4-3',
        sender: 'Mrs. Wang',
        text: 'Yes! You have no money, no family, nothing!',
        vocabs: [],
        isImage: false,
      },
      {
        id: 'msg-4-4',
        sender: 'Meimei',
        text: "Actually, I'm the daughter of Wang Industries' chairman.",
        vocabs: [],
        isImage: false,
      },
      {
        id: 'msg-4-5',
        sender: 'Mrs. Wang',
        text: 'Wang Industries? The biggest company in the city?',
        vocabs: [],
        isImage: false,
      },
      {
        id: 'msg-4-6',
        sender: 'Meimei',
        text: "Yes. And I'm very *powerful* in the business world.",
        vocabs: [{ word: 'powerful', type: 'highlight' }],
        isImage: false,
      },
      {
        id: 'msg-4-7',
        sender: 'Mrs. Wang',
        text: "Why didn't you tell us?",
        vocabs: [],
        isImage: false,
      },
      {
        id: 'msg-4-8',
        sender: 'Meimei',
        text: "I wanted to see if you'd accept me for who I am.",
        vocabs: [],
        isImage: false,
      },
      {
        id: 'msg-4-9',
        sender: 'Mrs. Wang',
        text: 'I'm so sorry! I was wrong!',
        vocabs: [],
        isImage: false,
      },
      {
        id: 'msg-4-10',
        sender: 'Meimei',
        text: "Now you're *afraid*? Too late. I'm divorcing your son.",
        vocabs: [{ word: 'afraid', type: 'highlight' }],
        isImage: false,
      },
    ],
  },
  {
    id: 5,
    title: "The Intern's Secret",
    hook: "They bullied the new intern, not knowing she's the chairman's daughter",
    genre: 'workplace',
    coverImage: '/images/drama-5.jpg',
    messages: [
      {
        id: 'msg-5-1',
        sender: 'Manager Li',
        text: "You're so *stupid*! Can't you do anything right?",
        vocabs: [{ word: 'stupid', type: 'highlight' }],
        isImage: false,
      },
      {
        id: 'msg-5-2',
        sender: 'Xiaoyu',
        text: "I'm still learning.",
        vocabs: [],
        isImage: false,
      },
      {
        id: 'msg-5-3',
        sender: 'Manager Li',
        text: "You'll never succeed here. Just quit!",
        vocabs: [],
        isImage: false,
      },
      {
        id: 'msg-5-4',
        sender: 'Xiaoyu',
        text: "Actually, I'm the chairman's daughter. I came here to see how you treat employees.",
        vocabs: [],
        isImage: false,
      },
      {
        id: 'msg-5-5',
        sender: 'Manager Li',
        text: "What? No, that can't be true!",
        vocabs: [],
        isImage: false,
      },
      {
        id: 'msg-5-6',
        sender: 'Xiaoyu',
        text: "I'm very *intelligent*. I recorded everything you said.",
        vocabs: [{ word: 'intelligent', type: 'highlight' }],
        isImage: false,
      },
      {
        id: 'msg-5-7',
        sender: 'Manager Li',
        text: 'Please! I have a family! I need this job!',
        vocabs: [],
        isImage: false,
      },
      {
        id: 'msg-5-8',
        sender: 'Xiaoyu',
        text: "You're *fired*. Security will escort you out.",
        vocabs: [{ word: 'fired', type: 'highlight' }],
        isImage: false,
      },
      {
        id: 'msg-5-9',
        sender: 'Manager Li',
        text: 'I'm sorry! Give me one more chance!',
        vocabs: [],
        isImage: false,
      },
    ],
  },
]
